from tkinter import *
raiz = Tk()
raiz.title('Agente inteligente')
raiz.iconbitmap("hp.ico")
raiz.geometry('750x850')
raiz.config(bg='orange')
miframe = Frame()
miframe.pack(side="bottom",anchor='n')
miframe.config(width='550',height='650')
miframe.config(bg='red')
miframe.config(bd=20)
miframe.config(relief="groove")
miframe.config(cursor="pirate")
milabel = Label(miframe,text='¿A que casa de Harry Potter perteneces? ',fg="black",font=(18))
milabel.place(x=100,y=100)
#milabel.pack()
raiz.mainloop()